# -*- coding: utf-8 -*-
"""Copy of modeling_walkthrough.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6trmjYFBOSw8wfYiQf60DGYcrwfPgUh

CONFIG FILE
"""
DATA_PATH = "/datasets/"
DATASET_1 = 'sales.csv'
DATASET_2 = 'sensor_stock_levels.csv'
DATASET_3 = 'sensor_storage_temperature.csv'
DROP_COLS = ['Unnamed: 0']
PRODUCT_CATEGORIES_COLS = ['product_id', 'category']
PRODUCT_PRICE_COLS = ['product_id', 'unit_price']
TIME_COL = 'timestamp'
MERGE_COLS = ['timestamp_day_of_month', 'timestamp_day_of_week', 'timestamp_hour']
TARGET = 'estimated_stock_pct'
K = 10
split = 0.75